// ChannelList Mutations Types
export const INCREMENT = 'INCREMENT'
export const FETCHING_CHANNEL_LIST = 'FETCHING_CHANNEL_LIST'
export const FETCHING_CHANNEL_LIST_SUCCESS = 'FETCHING_CHANNEL_LIST_SUCCESS'
export const FETCHING_CHANNEL_LIST_ERROR = 'FETCHING_CHANNEL_LIST_ERROR'
export const SAVE_SORTED_CHANNEL_LIST = 'SAVE_SORTED_CHANNEL_LIST'
export const SET_PROGRAMME_DATE = 'SET_PROGRAMME_DATE'

// Favourite
export const MODIFY_FAVOURITES = 'MODIFY_FAVOURITES'
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES'

// Channel
export const FETCHING_CHANNEL_DETAILS = 'FETCHING_CHANNEL_DETAILS'
export const FETCHING_CHANNEL_DETAILS_SUCCESS = 'FETCHING_CHANNEL_DETAILS_SUCCESS'
export const FETCHING_CHANNEL_DETAILS_ERROR = 'FETCHING_CHANNEL_DETAILS_ERROR'
export const CLEAR_CHANNEL_DETAILS = 'CLEAR_CHANNEL_DETAILS'
export const CACHE_CHANNEL_DETAILS = 'CACHE_CHANNEL_DETAILS'

// Programme
export const FETCHING_CHANNEL_LIST_PROGRAMME = 'FETCHING_CHANNEL_LIST_PROGRAMME'
export const FETCHING_CHANNEL_LIST_PROGRAMME_SUCCESS = 'FETCHING_CHANNEL_LIST_PROGRAMME_SUCCESS'
export const FETCHING_CHANNEL_LIST_PROGRAMME_ERROR = 'FETCHING_CHANNEL_LIST_PROGRAMME_ERROR'
